blog/urls.py
from . import views
from django.urls import path

app_name = "blog"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    #path('<slug:slug>/', views.DetailView.as_view(), name='detail'),
    path('/about/', views.AboutPageView.as_view(), name='about'),
    path('/contact/', views.ContactPageView.as_view(), name='contact'),
    path('<slug:slug>/', views.detail, name='detail'),
    

    

]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('blog/', include('blog.urls')),

    

]

#whenever this is true it's development mode when it's false in websit/settings.py it means its
# prodeuction mode and this is done whn website is live now
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE)
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    logo = models.FileField()
    

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from.forms import CommentForm

# Create your views here.
from django.views import generic
from .models import Post
from django.views.generic import TemplateView

class IndexView(generic.ListView):
    template_name = 'blog/index.html'

    def get_queryset(self):
        return Post.objects.filter(status=1).order_by('-created_on')

#class DetailView(generic.DetailView):
 #   model = Post
  #  template_name = 'blog/detail.html'

class AboutPageView(TemplateView):
    template_name = "blog/about.html"

class ContactPageView(TemplateView):
    template_name= "blog/contact.html"



def detail(request, slug):
    template_name = "blog/detail.html"
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
<style>
.image{
    height: 35vh;
    
}
</style>
<hr style="border: 0.2vh solid rgb(8, 8, 8); margin-bottom: 5vw;
    border-radius: 5px;">

<i><h4 style="text-align: center; font-weight: bolder; font-family:cursive; margin-top: 1vh; font-size: 3vh;">
    उड़ान की फिक्र नहीं, 
    हौसलों मे जान रखता हूँ ,<br>
    भीड से अलग ,
    मै अपनी पहचान रखता हूँ ।<br>
    </i></h4>

    <hr style="border: 0.1vh solid rgb(8, 8, 8); margin-bottom: 5vw;
    border-radius: 5px;"> 
    
    <h2 style="text-align:left; font-weight: bolder; font-size: 3vh; margin-left: 3vh;  margin-top: 1vh;">
      मनोज कान्हे 'शिवांश'
  </h2>

    <div class="card-body">
        
        
        

        <img src="https://lh3.googleusercontent.com/vRLYTH9LYpMV04qCs9WHRTHiMAvhEuVWeHdqf7O-qv_r0ImaSoGry0zvm0aEId52_5xbv2w4kURWoEMfp5sI3S6D4GWpFvAWGA220G2UZuSILpZ_HcIGv_Svk1HrXO0u2hn00BvoC6MynzK6uY4eR4LVmrtOKWaMUG76VqwcRfj4d6Upoj4rqdBTU_Jm7qru8EChya_mtSLdyUv2uVIUeyFEmMk4_wo9bEwyTu4xorZldhZGDv7TsZczmNtgU54W77Eyt4pzliCRFX_in3QYf4cgAFAa-phDwJk7fidEnQtKL7d8dySZA9FCfMdZ5WxdICbLwWSFxnRmIc8iJTfFM6pqio76IteuzoPX1ZHYWUNo90OnA_g2DpiL-iZeRfFPxSEiDJC7arrUZGtpiN6U03B-LAnJ_bHkmg59wH8hG4YoWrUhD4ThjryRvdhHxcEqoQVOZdGh93JrQYwcIlUyROU2j1Ntm9CaMrMDIt4eyX345hilqhHqy9ug4kRzEHPEtknLKcFF-gwXrlfkRAUxj7t9CYfn27t1gRdwkhT9IhyP8exlYqT7P4n9GShStCfFZEqxyNQl2580OLEswACe0TQYoCu4XPw8IRUkdS9ZRG0lBGJTnOppIBUTFjhxpI5DBQwLikuVx1lfTHR3yY_62ZH-1DguQ8mKSmp6Z7o_sOWZv5FjMVxG7S9A7Y40=w675-h883-no?authuser=0" class="image">
    </div>
    <h3 style="margin-left: 2vh; font-weight: 700;">साहित्यिक उपलब्धियाँ:--</h3>
    <p style="margin-left: 2.5vh; color: black; font-weight: 600;"> 
      जे. एम.ड़ी प्रकाशन दिल्ली द्वारा पुलवामा शहीदों को समर्पित पुस्तक <u>"भारत माता की जय"</u> मे रचनात्मक सहयोग के लिये अटल साहित्य
       अकादमी की ओर से <br> <u>"मातृभूमि सम्मान"</u></u> एवम् <u>"प्रतिभाशाली रचनाकार सम्मान"</u> ।
    </p>
    
    
   <!-- <div style="margin-top: 20vh ; margin-left: 10vw; margin-bottom: 3vw;">

    
    style="height: 35vh; width: 20vw; margin-left: 60vw; margin-bottom: 10vh; margin-top: -10vh; padding-top: 1vh;">
    </div>-->

    
    <br><br><br><br><br><br><br><br><br><br>



    {% endblock content %}
    

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html>

    <head>
        <title>@मनोज कान्हे 'शिवांश'</title>
        <link rel="stylesheet" type="text/css" href= "{% static 'blog/style.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-image: linear-gradient(to right, rgba(250, 222, 209, 0), rgb(243, 152, 109));
            
            

        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(8, 11, 196, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
            padding-bottom: 20vw;
            padding-top: 0.5vw;
        }
        .masthead {
            
            height: auto;
            color: rgb(29, 28, 28);
            padding-bottom: 15px;
           
            padding-top: 10px;
            color: black;
            padding-top: 1vw;
             }

             a:hover {
                color: red;
            }
        
    </style>

        <!-- Navigation -->
        <h5  class="font-weight-bold" style="margin-left: 1.8em; margin-top:2em; margin-top:-1em;"></h5>
        <nav class="navbar navbar-expand-sm bg-secondary navbar-dark " id="mainNav">
            <div class="container-fluid">
                
                <a class="navbar-brand font-weight-bold" href="{% url 'blog:index' %}" style="color: black; font-size: 2.1vh;">भारतीय राष्ट्रवादी मंच</a>
                
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Bharat-mata.png/220px-Bharat-mata.png" height="110vh" width="90vw" style="max-resolution: top 1vw; ;">
                    <a class="navbar-brand font-weight-bold" href="{% url 'blog:index' %}" style="color: black; font-size: 2.1vh;">मनोज कान्हे 'शिवांश'</a>
              
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold " style="color: black; font-size: 3vh;" href="{% url 'blog:about' %}">About</a>
                        </li>
                        
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold"style="color: black; font-size: 3vh;" href="{% url 'blog:contact' %}">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}


 <!-- Footer -->
        <br><br>&nbsp;

        <footer class="py-3 bg-grey">

            <hr>
            <p class="m-0 text-dark text-center ">Copyright &copy; @मनोज कान्हे 'शिवांश' </p>
        </footer>
    
    </body>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block content %}
<p style="text-align: center; padding-top: 6vw; font-size: 3vw; font-weight: bold;">
  You can connect with me on facebook and youtue for more such content</p>
<div class="fb-page"  style="padding-left: 27vw; padding-top: 4vw;">
    <a href="https://www.facebook.com/Manoj-Kanhey-Shivansh-106784087354006/">
      <img src="https://image.shutterstock.com/image-photo/kiev-ukraine-april-27-2015-260nw-278925056.jpg" height="100vw" width="120vw">
    </a>
    <a href="https://www.youtube.com/channel/UCDPCB1A2UdwCbI6b9FHntUg" style="padding-left: 10vw;">
      <img src="https://lh3.googleusercontent.com/proxy/QaAd28V9_gBlpOe9Etnad3s3M4sfMF-nBrez572F6JhTV98MrzkDJ18-EFuoeHfjnX3cMMk3dBgQsLiZX71d_a0_yYfbpnWreVVVu1O-9octWkjWBIU"  
      height="100vw" width="120vw" >
    </a>

</div>
      
      

  
  {% endblock content %}
  


  

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ post.title }}  {% endblock title %}</h1>
                    <a href="{% url 'blog:detail' post.id %}"><br>
                        {% if post.logo %}
                            <img src="{{ post.logo.url }}" class="img-responsive" height="200vh" width="150vw">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
        <p class=" text-muted" style="font-weight: bolder; color: black;">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | linebreaks }}</p>
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body" style="width: fit-content;">


        <!-- comments -->
        <p>{{ comments.count }} comments</p>

        {% for comment in comments %}
        <div class="comments" style="padding: 0.5vh;">
          <p class="font-weight-bold">
            {{ comment.name }}<br>
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert" style="font-size: 3vh;">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3 style="font-size: 4vh;">Leave a comment</h3>
        <hr style=" border: 0.1vh solid rgb(8, 8, 8);">
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
          <hr style=" border: 0.1vh solid rgb(8, 8, 8);">
        </form>

        {% endif %}
      </div>
    </div>



  </div>
</div>

{% endblock content %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}
<style>
    body {
        font-family: cursive;
        font-size: 1vw;
        background-image: linear-gradient(to right, rgba(185, 231, 231, 0), rgb(248, 138, 87));
    }
    
    .head_text {
        color: rgb(178, 235, 245);
    }
    
    .card {
        box-shadow: 0 16px 48px #080808;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <u><h3 class=" site-heading my-4 mt-3 text-black " style="font-weight: bolder;  text-align:center;  font-size:2.5vh ;color:rgb(92, 83, 8); color: black;"> भारतीय राष्ट्रवादी मंच : देश को समर्पित </h3></u>
                    
                     &nbsp

                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}

            
            <div class="card mb-4" style=" margin-left: -3vw; font-weight: bolder; background-color:rgb(229, 231, 233); color:rgb(4, 114, 218);">
                <div class="card-body">
                    <a href="{% url 'blog:detail' post.id %}"><br>
                        {% if post.logo %}
                            <img src="{{ post.logo.url }}" class="img-responsive" height="130vh" width="100vw">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                 

                <!--This .url will make sure that its the file object's path-->

                    <h2 class="card-title">{{ object.title }}</h2>
                    <p class="card-text text-muted h6" style="font-weight: bolder; color: black; font-size: 2vh;">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text" style="font-size: 2vh;">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'blog:detail' post.slug %}" class="btn btn-primary" style="width: 14vw; height: 3vh; font-size: 1.4vh; padding-bottom: 1vh; padding-top: 1vh;">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>
{%endblock%}